package com.android.dailycat.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity representing a cat post.
 *
 * This data class is annotated as an Entity for Room database, representing a cat post with an image,
 * a quote, and a favorite status. It includes an auto-generated primary key for unique identification.
 *
 * @property id The unique identifier for the cat post, auto-generated by the database. It can be null initially.
 * @property image The image of the cat post, stored as a ByteArray.
 * @property quote The quote associated with the cat post.
 * @property favorite A boolean flag indicating whether the cat post is marked as a favorite.
 */
@Entity(tableName = "favorites")
data class CatPost(
    @PrimaryKey(autoGenerate = true)
    var id: Int? = null,
    var image: ByteArray,
    var quote: String,
    var favorite: Boolean = false,
) {

    /**
     * Checks for equality between this CatPost and another object.
     *
     * The equality check considers all properties of the CatPost - image, quote, and favorite status.
     *
     * @param other The object to compare with this instance.
     * @return [Boolean] True if the objects are equal, false otherwise.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CatPost

        if (!image.contentEquals(other.image)) return false
        if (quote != other.quote) return false
        if (favorite != other.favorite) return false

        return true
    }

    /**
     * Generates a hash code for the CatPost.
     *
     * The hash code is generated based on the image, quote, and favorite status of the cat post.
     *
     * @return [Int] The hash code.
     */
    override fun hashCode(): Int {
        var result = image.contentHashCode()
        result = 31 * result + quote.hashCode()
        result = 31 * result + favorite.hashCode()
        return result
    }


}
